### ISSUE TITLE
StackedInline and collapse bug

### ISSUE THREAD

**Issue by P3RI9** [shinneider/django-admin-inline-paginator#21]
Hi! It worked as expected, thanks for the project! I only wanted to know if this pagination could be used with StackedInline instead of TabularInline. This would be perfect for my project.

Also, I don't know if it is a know bug but when you use classes=['collapse'] on the inline, the page numbers doesn't collapse, they keep out of it.
![image](https://user-images.githubusercontent.com/24256295/155492478-d0faa358-b7e5-4da4-9c73-242b8430d303.png)

**Comment by MrMika96** [comment]
I managed to add pagination to StackedInline by doing this
```python
class YourAdminInline(InlinePaginated, admin.StackedInline):
    model = YourModel
    per_page = 10
    template = f'{BASE_DIR}/templates/stacked_paginated.html' #path to your template
```
And then go to your template folder and create stacked_paginated.html like this:
```html
{% include 'admin/edit_inline/stacked.html' %}
<div class="admin-tabular-inline-pagination">
    {% include 'admin/tabular_paginator.html' %}
</div>
```

**Comment by maqnius** [comment]
Referring to the initial question, the pagination for collapsed inlines can be hidden using the following CSS

```css
div.inline-group + div.admin-tabular-inline-pagination {
    display: none;
}
div.inline-group:has(details[open]) + div.admin-tabular-inline-pagination {
    display: initial;
}
```
I thought it might help someone :)
